# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bigtext', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bigtext', models.TextField()),
                ('counter', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs', to='uuidsurrogate.A')),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bigtext', models.TextField()),
                ('counter', models.IntegerField(default=0)),
                ('grandparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs', to='uuidsurrogate.A')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs', to='uuidsurrogate.B')),
            ],
        ),
    ]
